### ISSUE TITLE
Versioning 

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/http-api#150]
We called this thing api-v1, but I expect when this is stable enough for an actual v1.x release we won't be finished. We really can't do major bumps in the Web api bc all clients would have to update. We also can't really create a new repository for every api major version, since most likely the breaking changes will not be that big, or will only be in one part (eg only in the websocket server). 

Instead, I think we should rename this to u-wave-http-api or something similar. All major versions will live in this repository side by side, and they'll all remain available on side by side routes. I have to look more into how other people do it, but right now I'm thinking that different Web api versions can call into the same controller files and use different controller methods only where the versions differ.

(brief bc on mobile)

**Comment by gnowxilef** [comment]
+1

**Comment by gnowxilef** [comment]
maybe http-api?
