### ISSUE TITLE
Figure out core/api-v1 separation

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/http-api#3]
Currently api-v1 contains _all_ of the things, and it's very tightly coupled with core. There should be a meaningful separation between the two so other plugins/interfaces/<insert name> can be added by server hosts easily, while keeping everything in sync.

Ideally we'd want some multiprocess support so we can have like millions of people online and do 0-downtime server upgrades (I mean, I assume that's how it works! not an expert. But we need to be able to do that, anyway.) in the long term.

Idea:
https://docs.google.com/drawings/d/1xq_F4mUoF0gsE_q5LW26fA2pElgTBf2zOKKkQaKq6AU/view

**Comment by gnowxilef** [comment]
why did you close this issue?
